version: '2'
services:
   jenkins:
      image: jenkins:local
      container_name: jenkins
      restart: always
      ports:
         - "8888:8080"
         - "50000:50000"
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock