version: '2'
services:
   jenkins:
      image: jenkins:local
      container_name: jenkins
      restart: always
      ports:
         - "8888:8080"
         - "50000:50000"
   gitlab:
      image: gitlab/gitlab-ce
      container_name: gitlab
      ports:
         - "4443:443"
         - "8889:80"
         - "222:22"